Setup env + jest
js-tasks-ru/nodejs-20220303_fotex200 pull request #1
Opened 2022-03-11 02:56 UTC by apushkarou

For some reason jest was not included in package json

2022-03-11 02:56 UTC, jsru commented
Спасибо за отправленный пулриквест, теперь @tadjik1 должен запустить тесты.

2022-03-12 12:36 UTC, tadjik1 commented
Я не использовал в задачнике jest, использовал другую библиотеку для тестирования - mocha. Расскажу об этом подробнее уже на следующем занятии.

2022-03-12 12:36 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-03-12 12:37 UTC, tadjik1 requested changes
Поправьте, пожалуйста, код с решением второй задачи

2022-03-12 12:37 UTC, tadjik1 commented on 02-event-loop/01-events-order/solutions.txt
> +1. James
Все сделано правильно в плане логики, но необходимо поправить небольшой нюанс - в строках не должно быть номеров. То есть должны быть лишь имена, иначе тесты не пройдут

2022-03-17 15:24 UTC, tadjik1 approved these changes

2022-03-17 15:39 UTC, merged